on: push
name: Testing deployment
jobs:
  web-deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.devotionalindia.org
        username: mohini@devotionalindia.org
        password: ${{ secrets.diko_ftp_password }}
        protocol: ftps
        port: 21